#!/usr/bin/env bash

set -e

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

dnf install -y i3 imlib2-devel xcompmgr xorg-x11-utils

pushd $tmp_dir || exit 1
git clone https://github.com/derf/feh.git
make
sudo make install
popd || exit 1

