#!/usr/bin/env bash

"$DEV_ENV"/package-install oracle-jdk@17 android-commandlinetools gradle

if [[ "$OSTYPE" == "darwin"* ]]; then
    export ANDROID_HOME="/opt/homebrew/share/android-commandlinetools"
#elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi

sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "emulator"
sdkmanager --licenses

