#!/usr/bin/env bash

grep="$OS"
dl_url="https://api.github.com/repos/jtroo/kanata/releases/latest"
dl="$(curl -s "$dl_url" | grep "browser_download_url" | cut -d '"' -f 4 | grep "$grep")"

# Download bin and put it somewhere
dlbin() {
    curl -fsSL -O "$1" || { echo "Download failed"; exit 1; }
    unzip "./$(basename "$1")" || { echo "Extraction failed"; rm "./$(basename "$1")"; exit 1; }
    bin="$(grep -l ^kanata -- * 2>/dev/null | grep -v cmd)"
    chmod +x "$bin"
    cp "$bin" "$2"
}

mkdir kanata
pushd kanata || exit 1
dlbin "$dl" "$HOME/.local/bin/kanata"
popd || exit 1
rm kanata

if [ "$OS" == "darwin" ]; then
    grep=macos
    brew install --cask karabiner-elements

    cp "$DEV_ENV"/resources/launchdaemons/com.kanata.plist /Library/LaunchDaemons/com.kanata.plist
    "$HOME"/.local/scripts/kanata-toggle enable
elif [ -z "$OS" ]; then
    echo "env var OS needs to be present"
    exit 1
fi

