name: Secret Scan
on:
  push:
    branches:
      - '**'
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read  # optional, for PR comments
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: "${{ github.event.before }}"
          head: HEAD
          extra_args: --debug --fail
        continue-on-error: true
